[package]
name = "photo_manager_server"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.81"
auto_impl = "1.2.0"
axum = { version = "0.7.5", features = ["http2", "macros", "multipart", "tracing"] }
axum-extra = { version = "0.9.3" }
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
dotenvy = "0.15.7"
futures = "0.3.30"
http-body-util = "0.1.2"
image = "0.25.2"
rand = "0.8.5"
sea-orm = { version = "1.0.0", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
sea-orm-migration = "1.0.0"
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0.124"
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }
tokio-util = { version = "0.7.11", features = ["io"] }
tower-http = { version = "0.5.2", features = ["fs", "limit", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
