[package]
name = "photo_manager_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.18", features = ["headers", "http2", "macros", "multipart", "tracing"] }
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.4.1", features = ["fs"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
